language: node_js
node_js:
  - "4.2.4"
install:
  - "npm install"
script:
  - "./node_modules/gulp/bin/gulp.js build"
  - "./node_modules/gulp/bin/gulp.js lint"
  - "./node_modules/gulp/bin/gulp.js test"
after_success:
  - "./node_modules/codecov/bin/codecov"
