language: node_js
node_js:
  - "0.12"
install:
  - "npm install"
  - "bower install"
script:
  - "./node_modules/gulp/bin/gulp.js build"
  - "./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha"
after_success:
  - "./node_modules/.bin/codecov"
